### ISSUE TITLE
IllegalBlockSizeException when decrypt

### ISSUE THREAD

**Issue by Dolanpls** [philipplackner/AndroidCrypto#1]
Hi Philipp!

I'm trying to create a test class for your 'CryptoManager' and for do that I created a long file in the resources folder.
The test is just to ensure that the encrypt and decrypt methods are working but once I call the decrypt method I have an error:

```
javax.crypto.IllegalBlockSizeException
at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:513)
at javax.crypto.Cipher.doFinal(Cipher.java:1736)
at com.plcoding.androidcrypto.CryptoManager.decrypt(CryptoManager.kt:74)
at com.plcoding.androidcrypto.CryptoManagerTest.decrypt(CryptoManagerTest.kt:55)
... 32 trimmed
Caused by: android.security.KeyStoreException: Invalid input length
at android.security.KeyStore.getKeyStoreException(KeyStore.java:695)
at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
... 36 more
```

Here is my test class:

```
package com.plcoding.androidcrypto

import android.content.Context
import androidx.test.platform.app.InstrumentationRegistry
import java.io.File
import java.io.FileOutputStream
import java.io.InputStream
import java.nio.file.Files
import org.junit.After
import org.junit.Assert
import org.junit.Before
import org.junit.Test

class CryptoManagerTest {

    private lateinit var templateContents: String
    private lateinit var tempTemplate: File
    private lateinit var cryptoManager: CryptoManager

    @Before
    fun setUp() {
        val context: Context = InstrumentationRegistry.getInstrumentation().context
        val inputStream: InputStream = context.assets.open("template.txt")

        val size: Int = inputStream.available()
        val buffer = ByteArray(size)
        inputStream.read(buffer).toString()

        templateContents = String(buffer)
        tempTemplate = File(Files.createTempFile("", ".txt").toUri())
        cryptoManager = CryptoManager()
    }

    @After
    fun tearDown() {
        tempTemplate.delete()
    }

    @Test
    fun encrypt() {
        cryptoManager.encrypt(templateContents.toByteArray(), FileOutputStream(tempTemplate))

        if (tempTemplate.exists()) {
            val tempContents = readFileContents(tempTemplate)
            Assert.assertNotEquals(templateContents, tempContents, "Original and encrypted files contents are the same")
        } else {
            Assert.fail("Temporal template does not exists")
        }
    }

    @Test
    fun decrypt() {
        val context: Context = InstrumentationRegistry.getInstrumentation().context
        val inputStream: InputStream = context.assets.open("encryptedTemplate.txt")
        val encryptedByteArray = cryptoManager.decrypt(inputStream)
        val decryptedContent = String(encryptedByteArray)
        Assert.assertEquals(templateContents, decryptedContent, "Original and decrypted files contents are not the same")
    }

    private fun readFileContents(file: File): String = file.readText(Charsets.UTF_8)
}
```

I think that maybe it's because the file to read is very long? I'm attaching it

[encryptedTemplate.txt](https://github.com/philipplackner/AndroidCrypto/files/9626281/encryptedTemplate.txt)
[template.txt](https://github.com/philipplackner/AndroidCrypto/files/9626282/template.txt)

Thanks in advance

**Comment by Nucifera8472** [comment]
I also had problems with this code, but I was able to find a solution, maybe this also works for you. See here [https://github.com/philipplackner/AndroidCrypto/issues/2](https://github.com/philipplackner/AndroidCrypto/issues/2)
