### ISSUE TITLE
 javax.crypto.BadPaddingException

### ISSUE THREAD

**Issue by tadawul-dev** [philipplackner/AndroidCrypto#4]
javax.crypto.BadPaddingException
                                                                                                    	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:609)
                                                                                                    	at javax.crypto.Cipher.doFinal(Cipher.java:2056)
                                                                                                    	at com.plcoding.androidcrypto.CryptoManager.decrypt(CryptoManager.kt:74)
                                                                                                    	at com.plcoding.androidcrypto.MainActivity$onCreate$1$1$1$2$2.invoke(MainActivity.kt:69)
                                                                                                    	at com.plcoding.androidcrypto.MainActivity$onCreate$1$1$1$2$2.invoke(MainActivity.kt:67)
                                                                                                    	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:153)
                                                                                                    	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:142)
                                                                                                    	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:222)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:563)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:455)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:468)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:310)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:297)
                                                                                                    	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:179)
                                                                                                    	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:98)
                                                                                                    	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:97)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1280)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1230)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1169)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1905)
                                                                                                    	at android.app.Activity.dispatchTouchEvent(Activity.java:4263)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:15262)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6654)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6454)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5910)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5967)
2024-03-29 12:03:56.476 28090-28090 AndroidRuntime          com.plcoding.androidcrypto           E  	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5933)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6098)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5941)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6155)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5914)

**Comment by tadawul-dev** [comment]
duplicate
